services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug

volumes:
  cargo-cache:
