version: '3.8'

services:
  dotvm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
      - ENVIRONMENT=development
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    volumes:
      - ./docs:/app/docs
    ports:
      - "3002:3000"
    command: [ "mdbook", "serve", "--hostname", "0.0.0.0", "--port", "3000" ]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

volumes:
  cargo-cache: