[package]
name = "search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Indexing and query services"

[lib]
path = "src/lib.rs"

[dependencies]
core = { path = "../core" }
object_model = { path = "../object_model" }
